export const LOGIN_FETCH_REQUESTED = 'LOGIN_FETCH_REQUESTED';
export const LOGIN_FETCH_FAILED = 'LOGIN_FETCH_FAILED';
export const LOGIN_FETCH_SUCCEEDED = 'LOGIN_FETCH_SUCCEEDED';

export const LOGOUT_FETCH_REQUESTED = 'LOGOUT_FETCH_REQUESTED';
export const LOGOUT_FETCH_FAILED = 'LOGOUT_FETCH_FAILED';
export const LOGOUT_FETCH_SUCCEEDED = 'LOGOUT_FETCH_SUCCEEDED';

export const USERS_LIST_FETCH_REQUESTED = 'USERS_LIST_FETCH_REQUESTED';
export const USERS_LIST_FETCH_FAILED = 'USERS_LIST_FETCH_FAILED';
export const USERS_LIST_FETCH_SUCCEEDED = 'USERS_LIST_FETCH_SUCCEEDED';

export const DISABLE_USER_FETCH_REQUESTED = 'DISABLE_USER_FETCH_REQUESTED';
export const DISABLE_USER_FETCH_FAILED = 'DISABLE_USER_FETCH_FAILED';
export const DISABLE_USER_FETCH_SUCCEEDED = 'DISABLE_USER_FETCH_SUCCEEDED';
export const DISABLE_USER_FETCH_CANCEL = 'DISABLE_USER_FETCH_CANCEL';

export const COURSES_LIST_FETCH_REQUESTED = 'COURSES_LIST_FETCH_REQUESTED';
export const COURSES_LIST_FETCH_FAILED = 'COURSES_LIST_FETCH_FAILED';
export const COURSES_LIST_FETCH_SUCCEEDED = 'COURSES_LIST_FETCH_SUCCEEDED';

export const REMOVE_COURSE_FETCH_REQUESTED = 'REMOVE_COURSE_FETCH_REQUESTED';
export const REMOVE_COURSE_FETCH_FAILED = 'REMOVE_COURSE_FETCH_FAILED';
export const REMOVE_COURSE_FETCH_SUCCEEDED = 'REMOVE_COURSE_FETCH_SUCCEEDED';
export const REMOVE_COURSE_FETCH_SUCCEEDED_WITH_ERROR = 'REMOVE_COURSE_FETCH_SUCCEEDED_WITH_ERROR';
export const REMOVE_COURSE_CANCEL = 'REMOVE_COURSE_CANCEL';

export const WITHDRAWAL_LIST_FETCH_REQUESTED = 'WITHDRAWAL_LIST_FETCH_REQUESTED';
export const WITHDRAWAL_LIST_FETCH_FAILED = 'WITHDRAWAL_LIST_FETCH_FAILED';
export const WITHDRAWAL_LIST_FETCH_SUCCEEDED = 'WITHDRAWAL_LIST_FETCH_SUCCEEDED';

export const APPROVE_WITHDRAWAL_FETCH_REQUESTED = 'APPROVE_WITHDRAWAL_FETCH_REQUESTED';
export const APPROVE_WITHDRAWAL_FETCH_FAILED = 'APPROVE_WITHDRAWAL_FETCH_FAILED';
export const APPROVE_WITHDRAWAL_FETCH_SUCCEEDED = 'APPROVE_WITHDRAWAL_FETCH_SUCCEEDED';
export const APPROVE_WITHDRAWAL_FETCH_CANCEL = 'APPROVE_WITHDRAWAL_FETCH_CANCEL';
