export const SUCCESS_STATUS = 'COURSE_REMOVE_SUCCESS_STATUS';
export const ERROR_STATUS = 'COURSE_REMOVE_ERROR_STATUS';
export const NETWORK_ERROR_STATUS = 'NETWORK_ERROR_STATUS';
export const NONE_STATUS = 'COURSE_REMOVE_NONE_STATUS';
